server:
  port: 8080 #端口号
spring:
  #静态资源放行
  mvc:
    static-path-pattern: static/**
  #数据源
  datasource:
    #修改DATA NAME PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DATA?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: NAME
    password: PASSWORD