server:
  port: 8081 #端口号
spring:
  #整合redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 10
        min-idle: 0
  #数据源
  datasource:
    #修改DATA NAME PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tim-admin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
#解决版本冲突问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#邮件发送
  mail:
    host: smtp.qq.com
    port: 587
    username: albustimbrown@qq.com
    password: #授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
#MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl